


import logging
from typing import Optional, Tuple

from gpuops.config.config import Config
from gpuops.client import ClientSet
from gpuops.client.worker_manager_clients import (
    WorkerStatusClient,
    WorkerRegistrationClient,
)
from gpuops.config.registration import (
    registration_client,
    read_worker_token,
    write_worker_token,
)
from gpuops.worker.collector import WorkerStatusCollector
from gpuops.schemas.config import PredefinedConfigNoDefaults
from gpuops.schemas.workers import WorkerCreate, WorkerRegistrationPublic, WorkerUpdate
from gpuops.utils import platform
from gpuops.utils.uuid import (
    set_worker_name,
    get_worker_name,
    set_legacy_uuid,
)

logger = logging.getLogger(__name__)

class WorkerManager:
    
    _is_embedded: bool
    _collector: WorkerStatusCollector
    _registration_client: WorkerRegistrationClient
    _clientset: Optional[ClientSet] = None
    
    def __init__(
        self,
        cfg: Config,
        is_embedded: bool,
        collector: WorkerStatusCollector,
    ):
        
        self._cfg = cfg
        self._is_embedded = is_embedded
        self._collector = collector
        worker_token = read_worker_token(self._cfg.data_dir) # type: ignore
        if worker_token:
            self._prepare_clients(worker_token)
            
    def _prepare_clients(self, token: str):
        self._clientset = ClientSet(
            base_url=self._cfg.get_server_url(),
            api_key=token,
        )
        self._status_client = WorkerStatusClient(self._clientset.http_client)
    
    async def register_with_server(
        self
    ) -> Tuple[ClientSet, Optional[PredefinedConfigNoDefaults]]:
        # always re-register the worker and retrive the token and config
        try:
            worker_registerred = self._register_worker()
            token = worker_registerred.token
            write_worker_token(self._cfg.data_dir, token) # type: ignore
            self._prepare_clients(token)
            return self._clientset, worker_registerred.worker_config # type: ignore
        except Exception as e:
            logger.error(f"Failed to register worker: {e}")
            raise
        
    def _register_worker(self) -> WorkerRegistrationPublic:
        name = self._cfg.worker_name or get_worker_name(self._cfg.data_dir) # type: ignore
        logger.info(
            f"Registering worker with name: {name or '<auto-generated-name>'}"
        )
        if self._is_embedded:
            # always reloads the token
            self._cfg.reload_token()
        self._registration_client = registration_client(
            data_dir=self._cfg.data_dir, # type: ignore
            server_url=self._cfg.get_server_url(),
            registration_token=self._cfg.token,
            wait_token_file=self._is_embedded,
        )
        
        workerStatus = self._collector.timed_collect(initial=True)
        # Set empty name if not specified to avoid validation error
        workerUpdate = WorkerUpdate(
            name=name or "",
            labels=self._ensure_builtin_labels(),
        )
        to_register = WorkerCreate.model_validate(
            {
                **workerStatus.model_dump(),
                **workerUpdate.model_dump(),
            }
        )
        created = self._registration_client.create(to_register)
        logger.info(f"Worker {created.name} registered with worker_id {created.id}.")
        
        set_worker_name(self._cfg.data_dir, created.name) # type: ignore
        set_legacy_uuid(self._cfg.data_dir, created.worker_uuid) # type: ignore
        
        return created
    
    def _ensure_builtin_labels(self) -> dict:
        labels = {
            "os": platform.system(),
            "arch": platform.arch(),
        }
        # worker name label will be set during registration
        name = self._cfg.worker_name or get_worker_name(self._cfg.data_dir) # type: ignore
        if name:
            labels["worker-name"] = name
        
        return labels